// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID                    uuid.UUID          `json:"id"`
	VerificationSessionID uuid.UUID          `json:"verification_session_id"`
	TaskType              string             `json:"task_type"`
	Payload               []byte             `json:"payload"`
	CreatedAt             time.Time          `json:"created_at"`
	PublishedAt           pgtype.Timestamptz `json:"published_at"`
	ClaimToken            pgtype.UUID        `json:"claim_token"`
	ClaimedUntil          pgtype.Timestamptz `json:"claimed_until"`
	AttemptCount          int32              `json:"attempt_count"`
	LastErrorCode         pgtype.Text        `json:"last_error_code"`
}

type PersonalDetail struct {
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	FullName              string    `json:"full_name"`
	DateOfBirth           time.Time `json:"date_of_birth"`
	IdentityNumber        string    `json:"identity_number"`
	Address               string    `json:"address"`
	CreatedAt             time.Time `json:"created_at"`
}

type SessionEvent struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	EventType  string    `json:"event_type"`
	Metadata   []byte    `json:"metadata"`
	OccurredAt time.Time `json:"occurred_at"`
}

type UploadIntent struct {
	ID                    uuid.UUID          `json:"id"`
	VerificationSessionID uuid.UUID          `json:"verification_session_id"`
	Kind                  string             `json:"kind"`
	StorageKey            string             `json:"storage_key"`
	Status                string             `json:"status"`
	CreatedAt             time.Time          `json:"created_at"`
	LatestStatusChangeAt  time.Time          `json:"latest_status_change_at"`
	ExpiresAt             time.Time          `json:"expires_at"`
	ConfirmedAt           pgtype.Timestamptz `json:"confirmed_at"`
	ObjectDeletedAt       pgtype.Timestamptz `json:"object_deleted_at"`
	FailureCode           pgtype.Text        `json:"failure_code"`
}

type VerificationArtifact struct {
	ID                    uuid.UUID `json:"id"`
	UploadIntentID        uuid.UUID `json:"upload_intent_id"`
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	Kind                  string    `json:"kind"`
	StorageKey            string    `json:"storage_key"`
	ContentType           string    `json:"content_type"`
	SizeBytes             int64     `json:"size_bytes"`
	Etag                  string    `json:"etag"`
	CreatedAt             time.Time `json:"created_at"`
}

type VerificationSession struct {
	ID                     uuid.UUID          `json:"id"`
	Status                 string             `json:"status"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	ResumeTokenHash        []byte             `json:"resume_token_hash"`
	ExpiresAt              time.Time          `json:"expires_at"`
	VerificationDeadlineAt pgtype.Timestamptz `json:"verification_deadline_at"`
	VerifiedAt             pgtype.Timestamptz `json:"verified_at"`
	RejectedAt             pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason        pgtype.Text        `json:"rejection_reason"`
}

type WebhookEvent struct {
	ID                uuid.UUID          `json:"id"`
	ReportedSessionID uuid.UUID          `json:"reported_session_id"`
	Payload           []byte             `json:"payload"`
	CreatedAt         time.Time          `json:"created_at"`
	ProcessingStatus  pgtype.Text        `json:"processing_status"`
	IgnoreReason      pgtype.Text        `json:"ignore_reason"`
	ReceivedAt        time.Time          `json:"received_at"`
	ProcessedAt       pgtype.Timestamptz `json:"processed_at"`
}
