// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type PersonalDetail struct {
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	FullName              string    `json:"full_name"`
	DateOfBirth           time.Time `json:"date_of_birth"`
	IdentityNumber        string    `json:"identity_number"`
	Address               string    `json:"address"`
	CreatedAt             time.Time `json:"created_at"`
}

type SessionEvent struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	EventType  string    `json:"event_type"`
	Metadata   []byte    `json:"metadata"`
	OccurredAt time.Time `json:"occurred_at"`
}

type VerificationSession struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
}
