// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type VerificationSession struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
}
