// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertUnpublishedOutbox = `-- name: InsertUnpublishedOutbox :exec
insert into outbox (
  id,
  verification_session_id,
  task_type,
  payload
) values (
  $1,
  $2,
  'provider:submit',
  jsonb_build_object('sessionId', $2::uuid)
)
`

type InsertUnpublishedOutboxParams struct {
	ID                    uuid.UUID `json:"id"`
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
}

// ISSUE 009 CHECKPOINT 1 — USER-OWNED QUERY SCAFFOLD
//
// Add the first unpublished provider:submit outbox insert named query here. Keep its
// JSON payload identifier-only and supply its UUID from application code.
func (q *Queries) InsertUnpublishedOutbox(ctx context.Context, arg InsertUnpublishedOutboxParams) error {
	_, err := q.db.Exec(ctx, insertUnpublishedOutbox, arg.ID, arg.VerificationSessionID)
	return err
}
