// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_details.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPersonalDetailsBySessionID = `-- name: GetPersonalDetailsBySessionID :one
SELECT verification_session_id, full_name, date_of_birth, identity_number, address, created_at
FROM personal_details
WHERE verification_session_id = $1
`

func (q *Queries) GetPersonalDetailsBySessionID(ctx context.Context, verificationSessionID uuid.UUID) (PersonalDetail, error) {
	row := q.db.QueryRow(ctx, getPersonalDetailsBySessionID, verificationSessionID)
	var i PersonalDetail
	err := row.Scan(
		&i.VerificationSessionID,
		&i.FullName,
		&i.DateOfBirth,
		&i.IdentityNumber,
		&i.Address,
		&i.CreatedAt,
	)
	return i, err
}

const insertPersonalDetails = `-- name: InsertPersonalDetails :exec
INSERT INTO personal_details (
    verification_session_id,
    full_name,
    date_of_birth,
    identity_number,
    address,
    created_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPersonalDetailsParams struct {
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	FullName              string    `json:"full_name"`
	DateOfBirth           time.Time `json:"date_of_birth"`
	IdentityNumber        string    `json:"identity_number"`
	Address               string    `json:"address"`
	CreatedAt             time.Time `json:"created_at"`
}

func (q *Queries) InsertPersonalDetails(ctx context.Context, arg InsertPersonalDetailsParams) error {
	_, err := q.db.Exec(ctx, insertPersonalDetails,
		arg.VerificationSessionID,
		arg.FullName,
		arg.DateOfBirth,
		arg.IdentityNumber,
		arg.Address,
		arg.CreatedAt,
	)
	return err
}

const lockVerificationSessionForPersonalDetails = `-- name: LockVerificationSessionForPersonalDetails :one
SELECT id, status, resume_token_hash, expires_at, created_at, updated_at
FROM verification_sessions
WHERE id = $1
FOR UPDATE
`

type LockVerificationSessionForPersonalDetailsRow struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) LockVerificationSessionForPersonalDetails(ctx context.Context, id uuid.UUID) (LockVerificationSessionForPersonalDetailsRow, error) {
	row := q.db.QueryRow(ctx, lockVerificationSessionForPersonalDetails, id)
	var i LockVerificationSessionForPersonalDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResumeTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
