// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_submissions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const setPendingVerification = `-- name: SetPendingVerification :execrows

update verification_sessions
set 
  status = 'verification_pending',
  verification_deadline_at = $1::timestamptz + interval '24 hours',
  updated_at = $1::timestamptz
where status = 'biometric_capture_uploaded' and id = $2
`

type SetPendingVerificationParams struct {
	SubmittedAt time.Time `json:"submitted_at"`
	SessionID   uuid.UUID `json:"session_id"`
}

// ISSUE 009 CHECKPOINT 1 — USER-OWNED QUERY SCAFFOLD
//
// Add the guarded Verification Session lock/read and exact pending transition named
// queries here. Run sqlc generate; never edit generated Go manually.
func (q *Queries) SetPendingVerification(ctx context.Context, arg SetPendingVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPendingVerification, arg.SubmittedAt, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
