// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_verdicts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const updateSessionToRejected = `-- name: UpdateSessionToRejected :execrows
update verification_sessions
set
  status = 'rejected',
  rejected_at = $1,
  rejection_reason = $2,
  updated_at = $1
where id = $3 and status = 'verification_pending'
`

type UpdateSessionToRejectedParams struct {
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	SessionID       uuid.UUID          `json:"session_id"`
}

//  7. `[sql query][postgres adapter]` User menulis guarded rejected update dari
//     `verification_pending` ke `rejected` beserta `rejected_at` dan exact reason.
func (q *Queries) UpdateSessionToRejected(ctx context.Context, arg UpdateSessionToRejectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionToRejected, arg.RejectedAt, arg.RejectionReason, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionToVerified = `-- name: UpdateSessionToVerified :execrows


update verification_sessions
set
  status = 'verified',
  verified_at = $1,
  updated_at = $1
where id = $2 and status = 'verification_pending'
`

type UpdateSessionToVerifiedParams struct {
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	SessionID  uuid.UUID          `json:"session_id"`
}

// ISSUE 009 CHECKPOINT 5 — USER-OWNED QUERY SCAFFOLD
//
// Add the handwritten sqlc queries for locking a Verification Session and applying
// guarded verified/rejected terminal outcomes. Do not edit generated sqlc files.
//  6. `[sql query][postgres adapter]` User menulis guarded verified update dari
//     `verification_pending` ke `verified` beserta `verified_at`.
func (q *Queries) UpdateSessionToVerified(ctx context.Context, arg UpdateSessionToVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionToVerified, arg.VerifiedAt, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
