// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const appendSessionEvent = `-- name: AppendSessionEvent :one
INSERT INTO session_events (session_id, event_type, metadata, occurred_at)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, event_type, metadata, occurred_at
`

type AppendSessionEventParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	EventType  string    `json:"event_type"`
	Metadata   []byte    `json:"metadata"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) AppendSessionEvent(ctx context.Context, arg AppendSessionEventParams) (SessionEvent, error) {
	row := q.db.QueryRow(ctx, appendSessionEvent,
		arg.SessionID,
		arg.EventType,
		arg.Metadata,
		arg.OccurredAt,
	)
	var i SessionEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EventType,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listSessionEvents = `-- name: ListSessionEvents :many
SELECT id, session_id, event_type, metadata, occurred_at
FROM session_events
WHERE session_id = $1
ORDER BY occurred_at, id
`

func (q *Queries) ListSessionEvents(ctx context.Context, sessionID uuid.UUID) ([]SessionEvent, error) {
	rows, err := q.db.Query(ctx, listSessionEvents, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
