// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: upload_intents.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmUploadIntent = `-- name: ConfirmUploadIntent :execrows
update upload_intents
set status = 'confirmed', confirmed_at = $1, latest_status_change_at = $2
where status = 'pending' and id = $3
`

type ConfirmUploadIntentParams struct {
	UploadIntentConfirmedAt          pgtype.Timestamptz `json:"upload_intent_confirmed_at"`
	UploadIntentLatestStatusChangeAt time.Time          `json:"upload_intent_latest_status_change_at"`
	UploadIntentID                   uuid.UUID          `json:"upload_intent_id"`
}

func (q *Queries) ConfirmUploadIntent(ctx context.Context, arg ConfirmUploadIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmUploadIntent, arg.UploadIntentConfirmedAt, arg.UploadIntentLatestStatusChangeAt, arg.UploadIntentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUploadIntent = `-- name: InsertUploadIntent :exec
INSERT INTO upload_intents (
    id,
    verification_session_id,
    kind,
    storage_key,
    status,
    created_at,
    latest_status_change_at,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'pending',
    $5,
    $6,
    $7
)
`

type InsertUploadIntentParams struct {
	UploadIntentID        uuid.UUID `json:"upload_intent_id"`
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	Kind                  string    `json:"kind"`
	StorageKey            string    `json:"storage_key"`
	CreatedAt             time.Time `json:"created_at"`
	LatestStatusChangeAt  time.Time `json:"latest_status_change_at"`
	ExpiresAt             time.Time `json:"expires_at"`
}

func (q *Queries) InsertUploadIntent(ctx context.Context, arg InsertUploadIntentParams) error {
	_, err := q.db.Exec(ctx, insertUploadIntent,
		arg.UploadIntentID,
		arg.VerificationSessionID,
		arg.Kind,
		arg.StorageKey,
		arg.CreatedAt,
		arg.LatestStatusChangeAt,
		arg.ExpiresAt,
	)
	return err
}

const loadUploadIntent = `-- name: LoadUploadIntent :one

select id, verification_session_id, kind, storage_key, status, created_at, latest_status_change_at, expires_at, confirmed_at, object_deleted_at, failure_code
from upload_intents
where verification_session_id = $1 and id = $2
`

type LoadUploadIntentParams struct {
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	UploadIntentID        uuid.UUID `json:"upload_intent_id"`
}

// CHECKPOINT 3 STEP 4 — USER-AUTHORED SUCCESS-PATH QUERIES
//
// Add these queries one at a time and run `make sqlc-generate` after each:
//
// 1. LoadUploadIntent :one
//   - non-locking read used before external object storage/extractor calls;
//   - receives Verification Session ID and Upload Intent ID;
//   - enforces ownership with both identifiers;
//   - returns the same columns as LockUploadIntent.
//
// 2. ConfirmUploadIntent :execrows
//   - sets status to confirmed;
//   - sets confirmed_at and latest_status_change_at from the application time;
//   - updates only the requested ID in expected pending state;
//   - the adapter must reject any affected-row count other than one as stale.
//
// 3. MarkUploadIntentValidationFailed :execrows
//   - required by artifact.Transaction even though the current tracer follows the
//     accepted branch;
//   - sets status, failure_code, and latest_status_change_at;
//   - updates only the requested ID in expected pending state;
//   - the adapter must reject any affected-row count other than one as stale.
//
// Do not add create/supersede Upload Intent queries in this tracer. Those belong to
// the later create-upload behavior listed in the checkpoint plan.
func (q *Queries) LoadUploadIntent(ctx context.Context, arg LoadUploadIntentParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, loadUploadIntent, arg.VerificationSessionID, arg.UploadIntentID)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.VerificationSessionID,
		&i.Kind,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.LatestStatusChangeAt,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ObjectDeletedAt,
		&i.FailureCode,
	)
	return i, err
}

const lockUploadIntent = `-- name: LockUploadIntent :one
select id, verification_session_id, kind, storage_key, status, created_at, latest_status_change_at, expires_at, confirmed_at, object_deleted_at, failure_code
from upload_intents
where verification_session_id = $1 and id = $2
for update
`

type LockUploadIntentParams struct {
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	UploadIntentID        uuid.UUID `json:"upload_intent_id"`
}

// CHECKPOINT 3 STEP 3 — USER-AUTHORED FIRST QUERY (COMPLETE)
func (q *Queries) LockUploadIntent(ctx context.Context, arg LockUploadIntentParams) (UploadIntent, error) {
	row := q.db.QueryRow(ctx, lockUploadIntent, arg.VerificationSessionID, arg.UploadIntentID)
	var i UploadIntent
	err := row.Scan(
		&i.ID,
		&i.VerificationSessionID,
		&i.Kind,
		&i.StorageKey,
		&i.Status,
		&i.CreatedAt,
		&i.LatestStatusChangeAt,
		&i.ExpiresAt,
		&i.ConfirmedAt,
		&i.ObjectDeletedAt,
		&i.FailureCode,
	)
	return i, err
}

const markUploadIntentValidationFailed = `-- name: MarkUploadIntentValidationFailed :execrows
update upload_intents 
set status = 'validation_failed', failure_code = $1, latest_status_change_at = $2
where status = 'pending' and id = $3
`

type MarkUploadIntentValidationFailedParams struct {
	UploadIntentFailureCode          pgtype.Text `json:"upload_intent_failure_code"`
	UploadIntentLatestStatusChangeAt time.Time   `json:"upload_intent_latest_status_change_at"`
	UploadIntentID                   uuid.UUID   `json:"upload_intent_id"`
}

func (q *Queries) MarkUploadIntentValidationFailed(ctx context.Context, arg MarkUploadIntentValidationFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUploadIntentValidationFailed, arg.UploadIntentFailureCode, arg.UploadIntentLatestStatusChangeAt, arg.UploadIntentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedePendingUploadIntent = `-- name: SupersedePendingUploadIntent :execrows
UPDATE upload_intents
SET
    status = 'superseded',
    latest_status_change_at = $1
WHERE verification_session_id = $2
  AND kind = $3
  AND status = 'pending'
`

type SupersedePendingUploadIntentParams struct {
	SupersededAt          time.Time `json:"superseded_at"`
	VerificationSessionID uuid.UUID `json:"verification_session_id"`
	Kind                  string    `json:"kind"`
}

func (q *Queries) SupersedePendingUploadIntent(ctx context.Context, arg SupersedePendingUploadIntentParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedePendingUploadIntent, arg.SupersededAt, arg.VerificationSessionID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
