// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_sessions.sql

package sqlc

import (
	"context"
)

const insertVerificationSession = `-- name: InsertVerificationSession :one
INSERT INTO verification_sessions DEFAULT VALUES
RETURNING id, status, created_at, updated_at
`

func (q *Queries) InsertVerificationSession(ctx context.Context) (VerificationSession, error) {
	row := q.db.QueryRow(ctx, insertVerificationSession)
	var i VerificationSession
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
