// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationSession = `-- name: CreateVerificationSession :one
INSERT INTO verification_sessions (resume_token_hash, expires_at)
VALUES ($1, $2)
RETURNING id, status, resume_token_hash, expires_at, created_at, updated_at
`

type CreateVerificationSessionParams struct {
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
}

type CreateVerificationSessionRow struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) CreateVerificationSession(ctx context.Context, arg CreateVerificationSessionParams) (CreateVerificationSessionRow, error) {
	row := q.db.QueryRow(ctx, createVerificationSession, arg.ResumeTokenHash, arg.ExpiresAt)
	var i CreateVerificationSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResumeTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorizedVerificationSession = `-- name: GetAuthorizedVerificationSession :one
SELECT id, status, resume_token_hash, expires_at, created_at, updated_at
FROM verification_sessions
WHERE id = $1 AND resume_token_hash = $2
`

type GetAuthorizedVerificationSessionParams struct {
	ID              uuid.UUID `json:"id"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
}

type GetAuthorizedVerificationSessionRow struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetAuthorizedVerificationSession(ctx context.Context, arg GetAuthorizedVerificationSessionParams) (GetAuthorizedVerificationSessionRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedVerificationSession, arg.ID, arg.ResumeTokenHash)
	var i GetAuthorizedVerificationSessionRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResumeTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVerificationSessionByID = `-- name: GetVerificationSessionByID :one
SELECT id, status, resume_token_hash, expires_at, created_at, updated_at
FROM verification_sessions
WHERE id = $1
`

type GetVerificationSessionByIDRow struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	ResumeTokenHash []byte    `json:"resume_token_hash"`
	ExpiresAt       time.Time `json:"expires_at"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

func (q *Queries) GetVerificationSessionByID(ctx context.Context, id uuid.UUID) (GetVerificationSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getVerificationSessionByID, id)
	var i GetVerificationSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResumeTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const guardVerificationSessionState = `-- name: GuardVerificationSessionState :execrows
UPDATE verification_sessions
SET status = $1, updated_at = $2
WHERE id = $3 AND status = $4
`

type GuardVerificationSessionStateParams struct {
	NextState     string    `json:"next_state"`
	UpdatedAt     time.Time `json:"updated_at"`
	ID            uuid.UUID `json:"id"`
	ExpectedState string    `json:"expected_state"`
}

func (q *Queries) GuardVerificationSessionState(ctx context.Context, arg GuardVerificationSessionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, guardVerificationSessionState,
		arg.NextState,
		arg.UpdatedAt,
		arg.ID,
		arg.ExpectedState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockVerificationSessionByID = `-- name: LockVerificationSessionByID :one
SELECT id, status, resume_token_hash, expires_at, created_at, updated_at, verification_deadline_at
FROM verification_sessions
WHERE id = $1
FOR UPDATE
`

type LockVerificationSessionByIDRow struct {
	ID                     uuid.UUID          `json:"id"`
	Status                 string             `json:"status"`
	ResumeTokenHash        []byte             `json:"resume_token_hash"`
	ExpiresAt              time.Time          `json:"expires_at"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
	VerificationDeadlineAt pgtype.Timestamptz `json:"verification_deadline_at"`
}

func (q *Queries) LockVerificationSessionByID(ctx context.Context, id uuid.UUID) (LockVerificationSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, lockVerificationSessionByID, id)
	var i LockVerificationSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ResumeTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VerificationDeadlineAt,
	)
	return i, err
}
