// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_artifacts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertVerificationArtifact = `-- name: InsertVerificationArtifact :exec
insert into verification_artifacts(id, upload_intent_id, verification_session_id, kind, storage_key, content_type, size_bytes, etag, created_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertVerificationArtifactParams struct {
	VerificationArtifactID          uuid.UUID `json:"verification_artifact_id"`
	UploadIntentID                  uuid.UUID `json:"upload_intent_id"`
	VerificationSessionID           uuid.UUID `json:"verification_session_id"`
	VerificationArtifactKind        string    `json:"verification_artifact_kind"`
	VerificationArtifactStorageKey  string    `json:"verification_artifact_storage_key"`
	VerificationArtifactContentType string    `json:"verification_artifact_content_type"`
	VerificationArtifactSizeBytes   int64     `json:"verification_artifact_size_bytes"`
	VerificationArtifactEtag        string    `json:"verification_artifact_etag"`
	VerificationArtifactCreatedAt   time.Time `json:"verification_artifact_created_at"`
}

// CHECKPOINT 3 STEP 4 — USER-AUTHORED SUCCESS-PATH QUERY
//
// Write exactly one query for the accepted confirmation tracer:
func (q *Queries) InsertVerificationArtifact(ctx context.Context, arg InsertVerificationArtifactParams) error {
	_, err := q.db.Exec(ctx, insertVerificationArtifact,
		arg.VerificationArtifactID,
		arg.UploadIntentID,
		arg.VerificationSessionID,
		arg.VerificationArtifactKind,
		arg.VerificationArtifactStorageKey,
		arg.VerificationArtifactContentType,
		arg.VerificationArtifactSizeBytes,
		arg.VerificationArtifactEtag,
		arg.VerificationArtifactCreatedAt,
	)
	return err
}
