// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertWebhookEvent = `-- name: InsertWebhookEvent :one


insert into webhook_events (
  id,
  reported_session_id,
  payload,
  received_at
)
values (
  $1,
  $2,
  $3,
  $4
)
on conflict (id) do nothing
returning id
`

type InsertWebhookEventParams struct {
	WebhookEventID uuid.UUID `json:"webhook_event_id"`
	SessionID      uuid.UUID `json:"session_id"`
	Payload        []byte    `json:"payload"`
	ReceivedAt     time.Time `json:"received_at"`
}

// ISSUE 009 CHECKPOINT 5 — USER-OWNED QUERY SCAFFOLD
//
// Add the handwritten sqlc queries for inserting/detecting provider event IDs and
// marking an event applied or bounded ignored. Do not edit generated sqlc files.
// 5. `[sql query][postgres adapter]` User menulis insert-or-detect-duplicate Webhook
// Event query untuk exact provider `eventId`.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.WebhookEventID,
		arg.SessionID,
		arg.Payload,
		arg.ReceivedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const markWebhookEvents = `-- name: MarkWebhookEvents :execrows
update webhook_events
set
  processing_status = $1,
  processed_at = $2,
  ignore_reason = case
    when $1 = 'ignored' then $3
    else null
  end
where id = $4 and processing_status is null
`

type MarkWebhookEventsParams struct {
	ProcessingStatus pgtype.Text        `json:"processing_status"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	IgnoreReason     pgtype.Text        `json:"ignore_reason"`
	WebhookEventID   uuid.UUID          `json:"webhook_event_id"`
}

//  8. `[sql query][postgres adapter]` User menulis query untuk menandai event `applied`
//     atau bounded `ignored` di transaction yang sama.
func (q *Queries) MarkWebhookEvents(ctx context.Context, arg MarkWebhookEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookEvents,
		arg.ProcessingStatus,
		arg.ProcessedAt,
		arg.IgnoreReason,
		arg.WebhookEventID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
